/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgvferreteria.View;

/**
 *
 * @author USUARIO
 */
public class SGVFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form SGVFPrincipal
     */
    public SGVFPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMIUsuarios = new javax.swing.JMenu();
        jMUsuarios = new javax.swing.JMenu();
        jMUsuarioI = new javax.swing.JMenuItem();
        jMUsuarioL = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Gestion de Ventas Ferreteria");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 153, 255));
        setName("frPrincipal"); // NOI18N

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMIUsuarios.setText("Operaciones");

        jMUsuarios.setText("Gestion Usuarios");

        jMUsuarioI.setText("Individual");
        jMUsuarioI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMUsuarioIActionPerformed(evt);
            }
        });
        jMUsuarios.add(jMUsuarioI);

        jMUsuarioL.setText("Lote");
        jMUsuarioL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMUsuarioLActionPerformed(evt);
            }
        });
        jMUsuarios.add(jMUsuarioL);

        jMIUsuarios.add(jMUsuarios);

        jMenuBar1.add(jMIUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 856, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMUsuarioIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMUsuarioIActionPerformed
        // TODO add your handling code here:
        new pUsuarioIndividual().setVisible(true);
    }//GEN-LAST:event_jMUsuarioIActionPerformed

    private void jMUsuarioLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMUsuarioLActionPerformed
        // TODO add your handling code here:
           new pUsuarioLote().setVisible(true);
    }//GEN-LAST:event_jMUsuarioLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SGVFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SGVFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SGVFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SGVFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SGVFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMIUsuarios;
    private javax.swing.JMenuItem jMUsuarioI;
    private javax.swing.JMenuItem jMUsuarioL;
    private javax.swing.JMenu jMUsuarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
